/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ClientDemo;

import static ClientDemo.JDialogFamily.familyID;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *主类 
 * @author ChTimTsubasa
 */
public class JDialogIndividual extends javax.swing.JDialog {

    /**
     * Creates new form JDialogIndividual
     */
    
    String familyID;
    String indiID;
    FinalClient connection;
    ClientDemo demo;
    JDialog parent;
    ZigbeeServer ser;
    public JDialogIndividual(JDialog parent,ClientDemo demo, boolean modal,String familyID) {
        super(parent, modal);
        this.familyID=familyID;
        this.setTitle("个人登录");
        this.demo=demo;
        this.parent=parent;
        this.parent.setVisible(false);
        ser=new ZigbeeServer();
        initComponents();
        connection=new FinalClient();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jIndiAutoLogin = new javax.swing.JRadioButton();
        jIndiRmberPassword = new javax.swing.JRadioButton();
        jPasswordLabel1 = new javax.swing.JLabel();
        jIndiLogin = new javax.swing.JButton();
        jIndiForget = new javax.swing.JButton();
        jIndiIDLogin = new javax.swing.JTextField();
        家庭组用户名1 = new javax.swing.JLabel();
        jIndiPWLogin = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jIndiIDReg = new javax.swing.JTextField();
        jRegistConfirm = new javax.swing.JToggleButton();
        jIndiPWReg1 = new javax.swing.JPasswordField();
        jIndiPWReg2 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jIndiAutoLogin.setText("下次自动登录");

        jIndiRmberPassword.setText("记住密码");

        jPasswordLabel1.setText("密码");

        jIndiLogin.setText("登录");
        jIndiLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIndiLoginActionPerformed(evt);
            }
        });

        jIndiForget.setText("忘记密码？");

        jIndiIDLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIndiIDLoginActionPerformed(evt);
            }
        });

        家庭组用户名1.setText("个人用户名");

        jIndiPWLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIndiPWLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jIndiForget))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jIndiLogin))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(家庭组用户名1))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jPasswordLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jIndiIDLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(jIndiPWLogin))))
                .addContainerGap(113, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(174, 174, 174)
                            .addComponent(jIndiAutoLogin))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(64, 64, 64)
                            .addComponent(jIndiRmberPassword)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jIndiIDLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(家庭组用户名1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jIndiPWLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jIndiLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jIndiForget)
                .addGap(20, 20, 20))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(151, 151, 151)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jIndiAutoLogin)
                        .addComponent(jIndiRmberPassword))
                    .addContainerGap(77, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("个人登录", jPanel4);

        jLabel2.setText("个人用户名");

        jLabel4.setText("请再次输入密码");

        jLabel3.setText("密码");

        jRegistConfirm.setText("注册");
        jRegistConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegistConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jIndiIDReg, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jIndiPWReg2)
                            .addComponent(jIndiPWReg1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jRegistConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jIndiIDReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jIndiPWReg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jIndiPWReg2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jRegistConfirm)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("个人注册", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * 按下登录后触发的事件
 * @param evt 
 */
    private void jIndiLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIndiLoginActionPerformed
        if (evt.getSource().equals(jIndiLogin)){
            indiID=this.jIndiIDLogin.getText();
            if(true){//connection.userLog(familyID, indiID,jIndiPWLogin.getText())==1){
                JOptionPane.showMessageDialog(null,"登录成功");
                demo.indiID=indiID;
                ser.sendData("V");                
                this.dispose();
            }
            else {
                JOptionPane.showMessageDialog(null,"登录失败，请检查用户名密码");
            }
        }
    }//GEN-LAST:event_jIndiLoginActionPerformed
/**
 * 按下注册后触发的事件
 * @param evt 
 */
    private void jRegistConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegistConfirmActionPerformed
        indiID=this.jIndiIDReg.getText();
        if (evt.getSource().equals(jRegistConfirm)){
            if(jIndiPWReg1.getText().equals(jIndiPWReg2.getText())){
                if(true){//connection.userReg(familyID, indiID, jIndiPWReg1.getText())==1){
                    JOptionPane.showMessageDialog(null,"注册成功");
                }
                else 
                    JOptionPane.showMessageDialog(null,"注册失败");
            }
            else JOptionPane.showMessageDialog(null,"两次输入密码不一致");
        }
    }//GEN-LAST:event_jRegistConfirmActionPerformed

    private void jIndiPWLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIndiPWLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jIndiPWLoginActionPerformed

    private void jIndiIDLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIndiIDLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jIndiIDLoginActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton jIndiAutoLogin;
    private javax.swing.JButton jIndiForget;
    private javax.swing.JTextField jIndiIDLogin;
    private javax.swing.JTextField jIndiIDReg;
    private javax.swing.JButton jIndiLogin;
    private javax.swing.JPasswordField jIndiPWLogin;
    private javax.swing.JPasswordField jIndiPWReg1;
    private javax.swing.JPasswordField jIndiPWReg2;
    private javax.swing.JRadioButton jIndiRmberPassword;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jPasswordLabel1;
    private javax.swing.JToggleButton jRegistConfirm;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel 家庭组用户名1;
    // End of variables declaration//GEN-END:variables
}
